# étapes du CI/CD (on choisit le nom)
stages:
  - "Build"
  - "Test"
  - "Code Quality"
  - "Docker"
  - "Deploy"
services:
  - docker:dind

# liste des étapes
Build:
  tags:
    - "node"
  stage: "Build" # renseignement de l'étape au niveau du pipeline
  image: node # image docker a utiliser
  script: # scripts a lancer
    - npm install
    - npm run build


Integration:
  tags:
    - "node"
  stage: "Test"
  image: node
  script:
    - npm install
    - npm run test
  allow_failure: true

Sonar:
  tags:
    - "docker"
  stage: "Code Quality"
  image: sonarsource/sonar-scanner-cli
  script: 
  - sonar-scanner -Dsonar.projectKey=demo-angular -Dsonar.sources=. -Dsonar.host.url=http://sonar:7000 -Dsonar.login=0ea0194c47a60e7c5589bb6329ce05e11de11d1a

Docker_push:
  tags:
    - "docker"
  stage: "Docker"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t $CI_REGISTRY_USER/demo-angular .
    - docker push $CI_REGISTRY_USER/demo-angular

Azure_Deploy:
  stage: "Deploy"
  image: dind
  script:
    - echo "No deployment yet"